// Adicionar membro na familia
let member = [
    {name: 'Thiago',
    lastName: 'dos Santos Silva',
    birthDate: new Date (1985, 01, 12),
    gender: "Masculino",
    kinship: "Marido",
    deathDate: '',
    },
    {name: 'Sarita',
    lastName: 'Silva Carneiro',
    birthDate: new Date (1983, 08, 30),
    gender: "Feminino",
    kinship: "Esposa",
    deathDate: '',
    },
    {name: 'Doug',
    lastName: 'dos Santos',
    birthDate: new Date (2015, 04, 19),
    gender: "Macho",
    kinship: "1º Pet",
    deathDate: '',
    },
    {name: 'Funny',
    lastName: 'dos Santos',
    birthDate: new Date (2015, 05, 19),
    gender: "Fêmea",
    kinship: "2º Pet",
    deathDate: new Date (2022, 01, 28),
    },
    {name: 'Costelinha',
    lastName: 'Carneiro dos Santos',
    birthDate: new Date (2021, 11, 10),
    gender: "Fêmea",
    kinship: "3º Pet",
    deathDate: '',
    },
]
// export data
module.exports = member